In [8]:
import pandas as pd

In [9]:
from sklearn.model_selection import train_test_split

In [7]:
df = pd.read_csv("data.csv",encoding="latin-1")
df.head()

         PLAYER  YRS     G     AB     R     H  ...    BB    SO   SB   CS     BA  HOF
0       Ty Cobb   24  3035  11434  2246  4189  ...  1249   357  892  178  0.366    1
1   Stan Musial   22  3026  10972  1949  3630  ...  1599   696   78   31  0.331    1
2  Tris Speaker   22  2789  10195  1882  3514  ...  1381   220  432  129  0.345    1
3   Derek Jeter   20  2747  11195  1923  3465  ...  1082  1840  358   97  0.310    1
4  Honus Wagner   21  2792  10430  1736  3430  ...   963   327  722   15  0.329    1

[5 rows x 16 columns]

In [12]:
df=df.drop(columns=["PLAYER","CS"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB

In [16]:
df.describe().round()

         YRS       G       AB       R  ...      SO      SB     BA    HOF
count  465.0   465.0    465.0   465.0  ...   465.0   465.0  465.0  465.0
mean    17.0  2049.0   7511.0  1150.0  ...   847.0   196.0    0.0    0.0
std      3.0   354.0   1294.0   290.0  ...   489.0   182.0    0.0    0.0
min     11.0  1331.0   4981.0   601.0  ...     0.0     7.0    0.0    0.0
25%     15.0  1802.0   6523.0   936.0  ...   436.0    63.0    0.0    0.0
50%     17.0  1993.0   7241.0  1104.0  ...   825.0   137.0    0.0    0.0
75%     19.0  2247.0   8180.0  1296.0  ...  1226.0   285.0    0.0    1.0
max     26.0  3308.0  12364.0  2295.0  ...  2597.0  1406.0    0.0    2.0

[8 rows x 14 columns]

In [19]:
x1= df.iloc[:,0:13]
x1

     YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [18]:
x2= df.iloc[:,0:13]

In [20]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [21]:
scalerStandard= StandardScaler()
x1=scalerStandard.fit_transform(x1)

In [23]:
x1=pd.DataFrame(x1,columns=df.columns[0:13])

In [25]:
x1.head()

        YRS         G        AB  ...        SO        SB        BA
0  2.516295  2.786078  3.034442  ... -1.003628  3.832067  3.648290
1  1.792237  2.760655  2.677044  ... -0.309948 -0.649080  1.996159
2  1.792237  2.091184  2.075964  ... -1.283965  1.299723  2.657012
3  1.068180  1.972543  2.849554  ...  2.030966  0.892346  1.004881
4  1.430208  2.099658  2.257758  ... -1.065016  2.896201  1.901752

[5 rows x 13 columns]