In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [6]:
df= pd.read_csv(r"data.csv", encoding='latin-1')

In [8]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [9]:
X = df.drop(columns=["PLAYER","HOF"])

In [10]:
y= df["HOF"]

In [11]:
X.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329

In [14]:
X.shape

(465, 14)

In [15]:
x_train , x_test , y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
x_train.shape

(372, 14)

In [18]:
x_train.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000
mean,17.010753,2048.526882,7514.346774,1147.586022,2168.067204,381.255376,77.854839,197.887097,877.158602,780.892473,834.672043,195.032258,56.645161,0.288444
std,2.836020,359.608872,1293.124126,291.286912,414.856385,95.678746,47.958095,144.515151,493.051874,327.974695,486.213119,180.102903,46.660244,0.020682
min,11.000000,1331.000000,5472.000000,601.000000,1660.000000,177.000000,8.000000,14.000000,0.000000,239.000000,0.000000,8.000000,0.000000,0.246000
25%,15.000000,1798.750000,6531.500000,933.250000,1841.000000,313.000000,40.000000,75.000000,613.250000,527.000000,431.750000,59.750000,21.750000,0.273000
50%,17.000000,1988.000000,7221.000000,1099.000000,2076.500000,366.000000,66.500000,170.000000,963.000000,725.000000,787.000000,140.500000,51.000000,0.287000
75%,19.000000,2257.500000,8184.250000,1299.250000,2354.500000,436.250000,108.000000,291.000000,1207.250000,952.750000,1197.250000,285.000000,84.000000,0.299250
max,26.000000,3308.000000,12364.000000,2295.000000,3771.000000,792.000000,252.000000,755.000000,2297.000000,2190.000000,2597.000000,1406.000000,335.000000,0.358000

In [22]:
l1=[1,2]
l2=['a','b']
print(l1.append(l2))

None

In [21]:
l1

[1, 2, ['a', 'b']]